// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlRI2iP7UTtUWUjNnSsb3um3bKmAPYC0g',
    appId: '1:618042037453:web:d462a714a810c636a24584',
    messagingSenderId: '618042037453',
    projectId: 'instagram-clone-7dfd3',
    authDomain: 'instagram-clone-7dfd3.firebaseapp.com',
    storageBucket: 'instagram-clone-7dfd3.appspot.com',
    measurementId: 'G-VFLJWT742C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_LFb2TQQ1If1y9aMOnWScWqi-j8TmvY',
    appId: '1:618042037453:android:c2be1796777dbf4da24584',
    messagingSenderId: '618042037453',
    projectId: 'instagram-clone-7dfd3',
    storageBucket: 'instagram-clone-7dfd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiT7xSRV_hdyya6HCZK0B1XggjdtNIhbs',
    appId: '1:618042037453:ios:f69b3cfc99e539dfa24584',
    messagingSenderId: '618042037453',
    projectId: 'instagram-clone-7dfd3',
    storageBucket: 'instagram-clone-7dfd3.appspot.com',
    iosClientId: '618042037453-hs04i4qb2ugjau4kibho6vkujkkgvd5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiT7xSRV_hdyya6HCZK0B1XggjdtNIhbs',
    appId: '1:618042037453:ios:f69b3cfc99e539dfa24584',
    messagingSenderId: '618042037453',
    projectId: 'instagram-clone-7dfd3',
    storageBucket: 'instagram-clone-7dfd3.appspot.com',
    iosClientId: '618042037453-hs04i4qb2ugjau4kibho6vkujkkgvd5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneInstagram',
  );
}
